### ISSUE TITLE
GetAda for Homebrew

### ISSUE THREAD

**Issue by jquorning** [AJ-Ianozi/getada#3]
This is an idea:

I would like to:

```sh
brew install getada
```
; and then perhaps:

```sh
getada GNAT
getada LLVM
getada GNAT Studio
getada HAC
```

**Comment by AJ-Ianozi** [comment]
I like this idea.  My next goal is to get the uninstaller working (which means getting finishing the logging system so it knows what it's done in the first place).  Then I would definitely be on board for homebrew and perhaps looking at bringing in the other tooling.

**Comment by jquorning** [comment]
The problem with Homebrew is that it has no Ada compiler så GetAda-Homebrew should probably be some kind of script

**Comment by jquorning** [comment]
I have decided to create a new repository for this purpose:

https://github.com/jquorning/AdaNow
