### ISSUE TITLE
Suggestion: Rename to GetAdaNow

### ISSUE THREAD

**Issue by jquorning** [AJ-Ianozi/getada#4]
Have you seen this:

https://comp.lang.ada.narkive.com/sR2HTRI7/getadanow-com

**Comment by AJ-Ianozi** [comment]
A bit of context:

Over the summer, I was endeavoring to create a landing page for Ada. I came across getadanow but it didn't support ssl (a must these days in my opinion) and the site wouldn't load on my mobile phone (still doesn't). I was looking for something similar to rustup's page.

I registered getada.dev (which just points to Alire at the moment) but as fate would have it the community came together and created Ada-lang.io before my first release.

That's where I came up with the name getada for the installer.

If people are interested in using getadanow we can look into it, but I don't know the person who owns it and aren't affiliated with them at the moment. (Last thing I want to do is fracture things further)

**Comment by jquorning** [comment]
Ok.

I am in the other direction regarding fracturing; I do top-down starting a lot of organizations on *GitHub* ( four *Ada* ones at the moment! ) I grab the *GetAdaNow* brand and says sorry later, if necessary. A lot of initiative and creativity is lost trying to be friends with everyone.
It seems that Button has abandoned the *GetAdaNow* project, so I just pick up the spoon (name) and continue as if it were my own.
I guess I will split *GetAdaNow* out from your project and continue as a pure *Homebrew* project in *Ruby* (Separation of Concerns).
I wish you the best of luck with the *getada* project!

Regards, Jesper, DK
